### ISSUE TITLE
options don’t work at all

### ISSUE THREAD

**Issue by ghost** [bcomnes/jsonfeed-to-atom#17]
Seems like there is a convenient “options” argument mentioned in the documentation (for `feedURLFn`), but it doesn’t really seem to work.

It appears as if the problem is that, albeit it *is* implemented, the [export in `index.js`](https://github.com/bcomnes/jsonfeed-to-atom/blob/890238be845b474c4fffa4a9274d984817fe211e/index.js#L13) doesn’t acknowledge it, so it ends up always being assigned the default value.

**Comment by bcomnes** [comment]
Oh whoops. I think I fixed this in the rss version but never ported back to the atom version. Happy to get a fix in this week.

**Comment by ghost** [comment]
If you feel like you would like, I might be able to submit a pull request fixing it.

**Comment by bcomnes** [comment]
Yeah go for it!  Let me know if you change your mind and I can take a look.  https://github.com/bcomnes/jsonfeed-to-rss might be a good reference.
