### ISSUE TITLE
Attachements broken?

### ISSUE THREAD

**Issue by xriss** [bcomnes/jsonfeed-to-atom#2]
https://github.com/bcomnes/jsonfeed-to-atom/blob/master/jsonfeed-to-atom-object.js#L123

I think the values set here should all be attributes so @href @type @length

**Comment by bcomnes** [comment]
Closed by https://github.com/bcomnes/jsonfeed-to-atom/pull/3 Thank you!

**Comment by bcomnes** [comment]
🎉`jsonfeed-to-atom@1.1.2` 🎉
